### ISSUE TITLE
Combined model of TextBoxes + CRNN

### ISSUE THREAD

**Issue by ravikantb** [MhLiao/TextBoxes#1]
Hi,

Is there any plan to release TextBoxes + CRNN combined module or parts of it? 
Please let me know. Thanks.

**Comment by MhLiao** [comment]
@ravikantb Thank for your attention. 
The “TextBoxes + CRNN” combined module may be released later(eg. in several months). 
For now, we have no specific plan to release this part.

**Comment by ravikantb** [comment]
@MhLiao : Ah, I was kind of hoping that you would say 'TextBoxes+CRNN' is coming soon :) but I guess that's okay. Thanks anyway for this module :) 
I shall attempt at combining them myself. Would it be alright if I keep this thread open and ask any question I face implementing it here? Please feel free to close it if you feel otherwise.

**Comment by MhLiao** [comment]
@ravikantb That's all right. You can free to ask any questions.

**Comment by beyondli** [comment]
@ravikantb ,yes ,this already perfect work, other hopeS should be done by ourselives, +CRNN is  also my hope :)  ,but need we finish, that OK,
@MhLiao, Textbox code is very good job ,THANKS!
