### ISSUE TITLE
LMDB creating script

### ISSUE THREAD

**Issue by Godricly** [MhLiao/TextBoxes#10]
May I ask for the LMDB creating script for training? The path on comment seems missing. Thank you.

**Comment by zjuDebug** [comment]
@Godricly I do this two step
1. convert the SynthText to xml format
2. use the examples in https://github.com/weiliu89/caffe/tree/ssd to create LMDB file

**Comment by Godricly** [comment]
Thank you for the help. I got it done.

**Comment by pranayamhatre175** [comment]
Hi...I am new in caffe and i just know basic working of caffe. For single character recognition we just provide image path and label in train.txt and val.txt file. Can anyone please tell me in Textboxes what is format of train.txt and val.txt for creating lmdb? 

My train.txt file contains image path and annotation file path for coco dataset is it right ? and how can we open lmdb file which contains annotations ? 

Thank you.

**Comment by pranayamhatre175** [comment]
I used following code for reading LMDB file 

import caffe
import lmdb
import numpy as np
import cv2
import matplotlib.pyplot as plt
from caffe.proto import caffe_pb2


lmdb_file='/home/arha/workarea/ocr_project/cocotext/data/lmdb/coco_val_lmdb'
lmdb_env = lmdb.open(lmdb_file)
lmdb_txn = lmdb_env.begin()
lmdb_cursor = lmdb_txn.cursor()


datum = caffe_pb2.Datum()
for key, value in lmdb_cursor:
    datum.ParseFromString(value)

    label = datum.label
    print 'label=',label
    data = caffe.io.datum_to_array(datum)
    print data.shape
    print 'data=',data
    image = np.transpose(data, (1,2,0))
    cv2.imshow('cv2', image)
    cv2.waitKey(0)
    print('{},{}'.format(key, label))

And It is giving output as follow

label= 0
(0, 0, 0)
data= []
OpenCV Error: Assertion failed (size.width>0 && size.height>0) in imshow, file /home/arha/softwares/opencv-2.4.13/modules/highgui/src/window.cpp, line 261
Traceback (most recent call last):
  File "lm.py", line 28, in <module>
    cv2.imshow('cv2', image)
cv2.error: /home/arha/softwares/opencv-2.4.13/modules/highgui/src/window.cpp:261: error: (-215) size.width>0 && size.height>0 in function imshow


Please clear my doubts.

Thank you

**Comment by pankajkumar** [comment]
@Godricly Can you share the code for converting SynthText to xml format?

**Comment by Godricly** [comment]
You can do it following PASCAL format.

**Comment by ahmedmazari-dhatim** [comment]
Hello @Godricly & @zjuDebug ,
l have my own dataset. To create the LMBD file l need to
use the [](examples in https://github.com/weiliu89/caffe/tree/ssd)  only or l have to convert my dataset into xml format ?

If yes, how can l convert mydataset to xml formalt ?

Thank you a lot

**Comment by Godricly** [comment]
The xml first.

2017-07-11 0:02 GMT+08:00 ahmedmazari-dhatim <notifications@github.com>:

**Comment by ahmedmazari-dhatim** [comment]
@Godricly ,

Thank you for your answer. How can convert my dataset to xml format so ?

Thank you

**Comment by Godricly** [comment]
well. it depends on your dataset. That's not what I can help. The xml
format follows PASCAL format. You can refer to that one.
Best
Yan

2017-07-12 0:21 GMT+08:00 ahmedmazari-dhatim <notifications@github.com>:
