### ISSUE TITLE
ICDAR 2013 database 

### ISSUE THREAD

**Issue by azzouztr** [MhLiao/TextBoxes#11]
Dear All,

Could someone send me please the **ICDAR 2013 database + test_list.txt** needed to run **test-icdr13.py** because I didn't find it on the Internet.
Thanks in advance.

**Comment by Godricly** [comment]
You can download it from [here](http://rrc.cvc.uab.es).

**Comment by azzouztr** [comment]
@Godricly Thank you a lot

**Comment by kclim2** [comment]
which dataset from their new website http://rrc.cvc.uab.es/ i should download (i downloaded all the 2013 to 2015 challenge dataset but couldn't locate the test_list.txt.

**Comment by zacniewski** [comment]
You should create file test_list.txt in the right place. This file should contain a name of the image to test in every line, for example:
img_1.jpg
img_2.jpg
And so on. These names should be the same as the names in 'test_images' folder. So you can write a simple script to add lines with names to aforementioned text file.

**Comment by kclim2** [comment]
Thanks!

**Comment by vigneshvenkatapathy** [comment]
> You can download it from [here](http://rrc.cvc.uab.es).
Hai
How you download from there
