### ISSUE TITLE
Error in `python': double free or corruption (out) Error

### ISSUE THREAD

**Issue by azzouztr** [MhLiao/TextBoxes#12]
Dear all

I have tried to run test_icdar13.py but i got the following errors

![screenshot from 2017-03-08 10-34-38](https://cloud.githubusercontent.com/assets/6660323/23698207/f4f9d8a2-03ea-11e7-9a6f-9f5a16c4a899.png)

![screenshot from 2017-03-08 09-34-03](https://cloud.githubusercontent.com/assets/6660323/23696193/f3d3db10-03e2-11e7-8089-9c7523b87389.png)

Could someone help me please to resolve this issue

**Comment by MhLiao** [comment]
@azzouztr I do not konw the solution to your problem, but I noticed that the "success" has been printed before suffering the error.

**Comment by azzouztr** [comment]
@MhLiao To resolve this problem, I added **export LD_PRELOAD="/usr/lib/libtcmalloc.so.4"**  but now still a last error which is **Segmentation fault (core dumped)**
this error is displayed also after the "success" has been printed. 

![screenshot from 2017-03-08 18-52-10](https://cloud.githubusercontent.com/assets/6660323/23716446/a3d06c66-0430-11e7-9d82-b5a9e4fe85b7.png)

Could you give me some advice in order to resolve this issue 
Thank you in advance

**Comment by MhLiao** [comment]
@azzouztr You can first locate the line where the falut happend.
