### ISSUE TITLE
NameError: name 'get_labelname' is not defined

### ISSUE THREAD

**Issue by abdelDebug** [MhLiao/TextBoxes#13]
Dear @MhLiao 

I have tried to run **test_icdar13_multi_scale.py** but I have obtained the following issue

![screenshot from 2017-03-08 20-51-57](https://cloud.githubusercontent.com/assets/26285524/23721408/ee24dd72-0441-11e7-9236-4fb54726f6f9.png)

Could you please help me to resolve it

**Comment by MhLiao** [comment]
@abdelDebug You can just delete this row in the code.

**Comment by abdelDebug** [comment]
@MhLiao 
When I have deleted the row, I have obtained this error

![screenshot from 2017-03-09 11-07-19](https://cloud.githubusercontent.com/assets/26285524/23745505/c333126a-04b8-11e7-84f0-83756a8d859c.png)

How can I resolve this issue please. It seems that this error is related to the batch size

**Comment by MhLiao** [comment]
@abdelDebug Your GPU memory is not enough. Try to recduce the input size or use a GPU with enough memory.
