### ISSUE TITLE
GPU memory (with / without cudnn)

### ISSUE THREAD

**Issue by HerShawn** [MhLiao/TextBoxes#15]
@MhLiao hello,
Could you please tell me the GPU memory needed to train or test your proposed method?
And how much free memory is required if i use cudnn?
Thank you very much!

**Comment by rremani** [comment]
Hi,
It also depends on your batch n iter size, for my case 6GB GPU RAM, batch size of 8 and iter size of 1 or 2 was working fine. Moment I took more than 8 batch size, I got memory error.
