### ISSUE TITLE
ERRO in running test_icdar13.py

### ISSUE THREAD

**Issue by shayuan** [MhLiao/TextBoxes#16]
@MhLiao There is an erro when running test_icdar13.py at line:
 net = caffe.Net(model_def,      # defines the structure of the model
                      model_weights,  # contains the trained weights
                      caffe.TEST)     # use test mode (e.g., don't perform dropout)

The console shows that:
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 758:14: Message type "caffe.LayerParameter" has no field named "norm_param".
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0404 18:15:56.743150 22335 upgrade_proto.cpp:79] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: /home/scw4750/TextBoxes/examples/TextBoxes/deploy.prototxt
*** Check failure stack trace: ***

It seems that it cannot parse the parameter field in **Layer: type: "Normalize"** in **deploy.prototxt**. How can I resolve this issue?

**Comment by MhLiao** [comment]
@shayuan You may use the wrong caffe root

**Comment by guddulrk** [comment]
Hi MhLiao,

I am trying to replicate your results and want to run this application on Windows 7 64 bit, with Python 3.5. When I am running test_icdar13.py, I am getting caffe errors. Could you please help me how can I run this application on windows?
Thanks.

**Comment by MhLiao** [comment]
@guddulrk What's your problem? I am wondering that my help may be limited because I never run such codes on Windows.

**Comment by guddulrk** [comment]
Thanks MhLiao for your reply. I am getting following error.

 from ._caffe import Net, SGDSolver

ImportError: DLL load failed: The specified module could not be found.

**Comment by shayuan** [comment]
@MhLiao  thank you. I have solved my issue. Finally I found my mistake is that the **downloaded zip** files   I used are not as the same as those from **git cloned**. Thank you anyway.

**Comment by yingning** [comment]
@shayuan , I have the same error ,but I can't get your meanings from your answer above.Can you give me a hand?  The following is my error:
ARNING: Logging before InitGoogleLogging() is written to STDERR
W0601 23:25:07.610895  6788 _caffe.cpp:122] DEPRECATION WARNING - deprecated use of Python interface
W0601 23:25:07.610927  6788 _caffe.cpp:123] Use this instead (with the named "weights" parameter):
W0601 23:25:07.610942  6788 _caffe.cpp:125] Net('/home/jsj/TextBoxes/examples/TextBoxes/deploy.prototxt', 1, weights='/home/jsj/TextBoxes/examples/TextBoxes/TextBoxes_icdar13.caffemodel')
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 758:14: Message type "caffe.LayerParameter" has no field named "norm_param".
F0601 23:25:07.612809  6788 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: /home/jsj/TextBoxes/examples/TextBoxes/deploy.prototxt
*** Check failure stack trace: ***
已放弃 (核心已转储)

**Comment by shayuan** [comment]
@yingning Be sure that your program is downloaded by using 'git clone ......' rather than  uncompressing the zip file from the wibsite. My first try was stuck here, hope that will help you.

**Comment by khalilo** [comment]
I'm sure that my program is downloaded by using 'git clone ...' but the same error is displayed again : 

WARNING: Logging before InitGoogleLogging() is written to STDERR
W0607 14:24:41.039604 12278 _caffe.cpp:139] DEPRECATION WARNING - deprecated use of Python interface
W0607 14:24:41.039634 12278 _caffe.cpp:140] Use this instead (with the named "weights" parameter):
W0607 14:24:41.039640 12278 _caffe.cpp:142] Net('/home/khalil/.local/install/caffe/TextBoxes/examples/TextBoxes/deploy.prototxt', 1, weights='/home/khalil/.local/install/caffe/TextBoxes/examples/TextBoxes/TextBoxes_icdar13.caffemodel')
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 758:14: Message type "caffe.LayerParameter" has no field named "norm_param".
F0607 14:24:41.040966 12278 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: /home/khalil/.local/install/caffe/TextBoxes/examples/TextBoxes/deploy.prototxt
*** Check failure stack trace: ***
Abandon (core dumped)

How can I resolve this issue? 
Thanks.

**Comment by yingning** [comment]
@shayuan ,I followed your advice that gitting clone the code ,and then adjust the path in test_icdar13.py .But I was not lucky for I was stucked in the same error.Thank you all the same!

**Comment by shayuan** [comment]
@yingning Adjusting the path in test_icdar13.py may be not enough, be sure that you have changed the caffe root into the python root, if not the caffe module you imported in python is the old version.

**Comment by shayuan** [comment]
@khalilo  Sorry, I'm a fresh hand in Caffe yet. My problem was caused by the version of the program. Maybe  your problem is in environment dependencies? Have you met some warinings or erros when building caffe or pycaffe?

**Comment by khalilo** [comment]
@shayuan No, I have to install the dependencies and run make pycaffe and I have not received any errors.
Which version of program you use it ?

**Comment by khalilo** [comment]
@shayuan And for  make -j8, make py commands,  it shows me Make: nothing to do "all" Make: nothing to do for "py", that's normal ?

**Comment by khalilo** [comment]
@shayuan It's good I solve the problem.
The problem is that I write the caffe path install in the system not the caffe project path TextBoxes.
But, I have another problem in path save_dir 

  File "test_icdar13.py", line 48, in <module>
    detection_result=open(save_detection_path,'wt')
IOError: [Errno 2] No such file or directory: '/media/khalil/3da753f7-bd2c-43d5-a1e2-485bd5667bcf/khalil/Documents/Project/VGG-caffe/TextBoxes/python/data/TextBoxes/test_bb/res_img_4.txt'

**Comment by khalilo** [comment]
It's good I solve the problem :+1:

**Comment by yingning** [comment]
@khalilo ,Could you mind telling me how to solve your problems mentioned above? Can  you share your test_icdar13.py ?I stucked here for a long time.Thank you in advance!
