### ISSUE TITLE
How to test TextBoxes using ICDAR2013 dataset?

### ISSUE THREAD

**Issue by RemexHu** [MhLiao/TextBoxes#17]
Hi,

I've downloaded the ICDAR2013 dataset (Task 2.1: Text Localization, 233 images and ground truth text files), but how can I generate test_list.txt?

**Comment by RemexHu** [comment]
By the way, I am a undergraduate student at USTC, and I chose TextBoxes as my graduation project. Could you please leave me an email account or wechat id that I could contact you directly? Thank you very much!

**Comment by RemexHu** [comment]
By the way, I am a undergraduate student at USTC, and I chose TextBoxes as my graduation project. Could you please leave me an email account or wechat id that I could contact you directly? Feel free to contact me via remexhu@icloud.com.

Thank you very much!

**Comment by RemexHu** [comment]
By the way, I am an undergraduate student at USTC, and I chose TextBoxes as my graduation project. Could you please leave me an email account or wechat id that I could contact you directly? Feel free to contact me via remexhu@icloud.com.

Thank you very much!

**Comment by MhLiao** [comment]
You can generate the test_list.txt by yourself. It is just a series of image path of the icdar2013 dataset.
