### ISSUE TITLE
如何在SSD路径下运行TextBoxes的model

### ISSUE THREAD

**Issue by LookingSky** [MhLiao/TextBoxes#19]
你好，TextBoxes在横向字符有很好的表现，但是我在ssd路径下运行TextBoxes的model, 出现了错误，与SSD网络相比,TextBoxes在data层缺少了distort_param，在loss缺少了ignor_cross_boudary_bbox与mini_type参数，我猜TextBoxes使用的ssd是否是老版ssd
错误是：
Check failed:num_priors_*num_loc_class_*4==bottom[0]->channels()(295112 vs.590224) Number of priors must match number of location predictions

**Comment by MhLiao** [comment]
The prior box layer of TextBoxes is different from which in SSD.
