### ISSUE TITLE
error with make runtest?

### ISSUE THREAD

**Issue by enjoyyi00** [MhLiao/TextBoxes#2]
i have make successfully
when i make runtest, it has this error
## Do you know why?
[----------] 3 tests from MultiBoxLossLayerTest/3, where TypeParam = caffe::GPUDevice<double>
[ RUN      ] MultiBoxLossLayerTest/3.TestConfGradient
F0122 10:41:19.059348 24720 multibox_loss_layer.cpp:143] Check failed: num_priors_ * loc_classes_ * 4 == bottom[0]->channels() (128 vs. 64) Number of priors must match number of location predictions.
*** Check failure stack trace: ***
    @     0x7f488e9d6b6d  google::LogMessage::Fail()
    @     0x7f488e9dab87  google::LogMessage::SendToLog()
    @     0x7f488e9d8a09  google::LogMessage::Flush()
    @     0x7f488e9d8d0d  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f488a7b6dc0  caffe::MultiBoxLossLayer<>::Reshape()
    @           0x55d82f  caffe::Layer<>::SetUp()
    @           0x55ee3f  caffe::GradientChecker<>::CheckGradientExhaustive()
    @           0x9d12d1  caffe::MultiBoxLossLayerTest_TestConfGradient_Test<>::TestBody()
    @           0xa804b3  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0xa782b7  testing::Test::Run()
    @           0xa7835e  testing::TestInfo::Run()
    @           0xa78465  testing::TestCase::Run()
    @           0xa7a6f8  testing::internal::UnitTestImpl::RunAllTests()
    @           0xa7a987  testing::UnitTest::Run()
    @           0x54942f  main
    @     0x7f4889a50bd5  __libc_start_main
    @           0x552149  (unknown)
make: *** [runtest] Aborted

**Comment by MhLiao** [comment]
@iFighting Thank you for your reminding. 
I have fixed the runtest problem in the newest update.

**Comment by enjoyyi00** [comment]
### new error

[----------] 12 tests from NesterovSolverTest/2, where TypeParam = caffe::GPUDevice<float>
[ RUN      ] NesterovSolverTest/2.TestNesterovLeastSquaresUpdateWithMomentum
*** Aborted at 1485074681 (unix time) try "date -d @1485074681" if you are using GNU date ***
PC: @     0x7f2b0774aa87 __memmove_ssse3_back
*** SIGSEGV (@0xa776000) received by PID 26402 (TID 0x7f2b13569740) from PID 175595520; stack trace: ***
    @     0x7f2b079cf160 (unknown)
    @     0x7f2b0774aa87 __memmove_ssse3_back
    @     0x7f2b0846719c std::vector<>::erase()
    @     0x7f2b084d6538 caffe::DevicePair::compute()
    @     0x7f2b084db37c caffe::P2PSync<>::Prepare()
    @     0x7f2b084db8fc caffe::P2PSync<>::Run()
    @           0x68e385 caffe::GradientBasedSolverTest<>::RunLeastSquaresSolver()
    @           0x69ed1b caffe::GradientBasedSolverTest<>::TestLeastSquaresUpdate()
    @           0x69f33e caffe::NesterovSolverTest_TestNesterovLeastSquaresUpdateWithMomentum_Test<>::TestBody()
    @           0xa68f33 testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0xa60d37 testing::Test::Run()
    @           0xa60dde testing::TestInfo::Run()
    @           0xa60ee5 testing::TestCase::Run()
    @           0xa63178 testing::internal::UnitTestImpl::RunAllTests()
    @           0xa63407 testing::UnitTest::Run()
    @           0x54724f main
    @     0x7f2b07633bd5 __libc_start_main
    @           0x54fd99 (unknown)
make: *** [runtest] Aborted

**Comment by MhLiao** [comment]
@iFighting I did not suffer such a error. 
You can just ignore these runtest errors, which would not influence the codes of TextBoxes.
