### ISSUE TITLE
Question about your multiscale input

### ISSUE THREAD

**Issue by wcy940418** [MhLiao/TextBoxes#20]
Thanks for excellent work. But I have a concern about your multiscale input. The PriorBox layers need specific input size to construct the default boxes, but in your multiscale test file, you just invoke the deploy.prototxt generated by SSD300 training file for all scales. Does it mean that in larger input scale (e.g. 700x700), the size of prior boxes are same with 300x300 and the only difference is the number of boxes? Thank you.

**Comment by MhLiao** [comment]
You are right. I did not change the size of prior boxes for other input scales, which is benefit to detect small texts.

**Comment by yushanshan05** [comment]
If I zoom in a image, the size of default boxes is not changed, so the small texts may be detected.  For example,  the image has a text of 15*30 and the minimal default  boxes  is  30*60. When I  zoom in the text to 30*60,  I could find the text. Am I it right?

**Comment by wcy940418** [comment]
@yushanshan05 Generally, yes.
