### ISSUE TITLE
detected results are not the same as shown in the paper!

### ISSUE THREAD

**Issue by HelloTobe** [MhLiao/TextBoxes#21]
@MhLiao  Hi,
i download the codes and run test_icdar13.py  with TextBoxes_icdar13.caffemodel on the ICDAR13 dataset 

(which contains 233  pictures), but some results (eg.  img_14, img_19, img_34)  are worse than the pictures 

present in your paper (Figure 3).

Could you help me find the reason.    Do you use multi-scale to produce the pictures shown in Figure 3 ?

Thanks in advance!

**Comment by MhLiao** [comment]
@HelloTobe 
Yes, I use multi-scale in the paper.

**Comment by HelloTobe** [comment]
@MhLiao Thank you.

**Comment by naivepark** [comment]
Hi MhLiao 
I download the codes and ready to run your code.
But i dont know where can i find this file -> [TextBoxes_icdar13.caffemodel] 
Where can i find this file?
Thanks
