### ISSUE TITLE
how to make ICDAR2013 dataset generate LMDB?

### ISSUE THREAD

**Issue by clscy** [MhLiao/TextBoxes#22]
Hi. I am not clear the process of ICDAR2013 dataset generating LMDB, could you explain it in detail. Thank you.

**Comment by MhLiao** [comment]
@clscy  You can follow the script "data/VOC0712/create_data.sh" on SSD to create the LMDB of ICDAR 2013.

**Comment by pankajkumar** [comment]
I have used following files to create the LMDB database 

[create_list.py](https://github.com/pankajkumar/TextBoxes/blob/pankaj/examples/TextBoxes/create_list.py
)
[create_data.sh](https://github.com/pankajkumar/TextBoxes/blob/pankaj/examples/TextBoxes/create_data.sh
)

create_list.py uses icdar2013.txt file which you can create yourself, it's just the list of all image files without jpg extension.

**Comment by clscy** [comment]
thank you very much @MhLiao @pankajkumar ,I have finished it.

**Comment by rayush7** [comment]
@clscy @pankajkumar Could you please explain how did you create annotations in the form of xml for ICDAR 2013 dataset?
