### ISSUE TITLE
Small objects detection

### ISSUE THREAD

**Issue by xiaodiu2010** [MhLiao/TextBoxes#24]
Hi, @MhLiao 
     I'm trying to re-implement your work in[ tensorflow](https://github.com/xiaodiu2010/TextBoxes-TensorFlow) . For now, i have got big process.  But the detection on small objects are quiet bad because small objects can't match default boxes  well, and they never got trained. 
     I tried to tune the anchor size but it does't work well. Could you give me some advices. 
Thanks a lot.

**Comment by MhLiao** [comment]
@xiaodiu2010 You can try to use larger input size for training.

**Comment by xiaodiu2010** [comment]
Sorry for reply late. 
@MhLiao  You mean, training with the input size of 700 * 700 performs best, right?
Then for multi-scale input, I need train 5 different models for each scale?

**Comment by MhLiao** [comment]
@xiaodiu2010  You actually do not need to train different models for each scale. The network is fully convolutional, so you can train different size with the same model. By the way, I do not know whether train different models for each scale is better. You can try both!
