### ISSUE TITLE
Multiclass implementation of Textboxes

### ISSUE THREAD

**Issue by Yash5595** [MhLiao/TextBoxes#26]
Hi,

I wanted to know if we can implement TextBoxes such that there are more than two possible classes? (currently the classes are text and background)
Thanks!

**Comment by MhLiao** [comment]
That is OK.

**Comment by Yash5595** [comment]
Thanks for the reply @MhLiao 
I have the annotation files corresponding to the multi-class implementation and  have updated the labelmap_voc.prototxt file for the new classes. Will these be sufficient to train the model and if not, can you please suggest me other possible changes required ?  
Thanks in advance!

**Comment by MhLiao** [comment]
You also need to modify the class_num parameter in the trainging script.
