### ISSUE TITLE
Failed to run make -j8

### ISSUE THREAD

**Issue by lomograb** [MhLiao/TextBoxes#29]
After I ran command `make -j8`, I'm getting this error :
`/usr/include/google/protobuf/arenastring.h:219:31: note:   candidate expects 1 argument, 0 provided
Makefile:575: recipe for target '.build_release/src/caffe/data_transformer.o' failed
make: *** [.build_release/src/caffe/data_transformer.o] Error 1
`
I'm using Ubuntu 16.04. Protobuf 3.2
Downgrading Protobuf to 3.1 also didn't work

**Comment by MhLiao** [comment]
@lomograb Can you install Caffe successfully in your system?

**Comment by lomograb** [comment]
Yes, I have done succesfully install Caffe on my system. But I'm not sure this is installation issue. Correct me please

**Comment by lomograb** [comment]
what version of Protobuf do you using ?

**Comment by MhLiao** [comment]
I use the 2.6.1 version.

**Comment by lomograb** [comment]
The only solution was dowgrade Ubuntu to Trusty Tahr which have gcc 4 as the default compiler. One more question: Could it be possible to reduce the recognition time ? I got 3 - 7 seconds for every execution
