### ISSUE TITLE
Error in running train_icdar13.py

### ISSUE THREAD

**Issue by khalilo** [MhLiao/TextBoxes#30]
@MhLiao There is an error when running train_icdar13.py.

The console shows that:
I0614 14:06:31.362638  9607 layer_factory.hpp:77] Creating layer data
I0614 14:06:31.371596  9607 net.cpp:100] Creating Layer data
I0614 14:06:31.371624  9607 net.cpp:408] data -> data
I0614 14:06:31.371659  9607 net.cpp:408] data -> label
F0614 14:06:31.371739  9610 db_lmdb.hpp:15] Check failed: mdb_status == 0 (2 vs. 0) No such file or directory
*** Check failure stack trace: ***
    @     0x7f2c227e95cd  google::LogMessage::Fail()
    @     0x7f2c227eb433  google::LogMessage::SendToLog()
    @     0x7f2c227e915b  google::LogMessage::Flush()
    @     0x7f2c227ebe1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f2c22df1350  caffe::db::LMDB::Open()
    @     0x7f2c22e2d276  caffe::DataReader<>::Body::InternalThreadEntry()
    @     0x7f2c1f4225d5  (unknown)
    @     0x7f2c1ecd06ba  start_thread
    @     0x7f2c2128782d  clone
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by MhLiao** [comment]
Did you generate your training data?

**Comment by khalilo** [comment]
How I can generate my training data.

**Comment by khalilo** [comment]
@MhLiao I generate the training database and I have this error :

I0614 18:01:33.495789 13626 layer_factory.hpp:77] Creating layer data
I0614 18:01:33.497731 13626 net.cpp:100] Creating Layer data
I0614 18:01:33.497809 13626 net.cpp:408] data -> data
I0614 18:01:33.497948 13626 net.cpp:408] data -> label
I0614 18:01:33.498134 13629 db_lmdb.cpp:35] Opened lmdb /media/khalil/3da753f7-bd2c-43d5-a1e2-485bd5667bcf/khalil/Documents/Project/VGG-caffe/TextBoxes/examples/TextBoxes/icdar_train_lmdb
F0614 18:01:33.514853 13626 data_transformer.cpp:810] Check failed: datum_channels > 0 (0 vs. 0) 
*** Check failure stack trace: ***
    @     0x7f4bbc29b5cd  google::LogMessage::Fail()
    @     0x7f4bbc29d433  google::LogMessage::SendToLog()
    @     0x7f4bbc29b15b  google::LogMessage::Flush()
    @     0x7f4bbc29de1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f4bbc86751a  caffe::DataTransformer<>::InferBlobShape()
    @     0x7f4bbc786375  caffe::AnnotatedDataLayer<>::DataLayerSetUp()
    @     0x7f4bbc77845a  caffe::BasePrefetchingDataLayer<>::LayerSetUp()
    @     0x7f4bbc860722  caffe::Net<>::Init()
    @     0x7f4bbc861fb1  caffe::Net<>::Net()
    @     0x7f4bbc8d2dfa  caffe::Solver<>::InitTrainNet()
    @     0x7f4bbc8d40f7  caffe::Solver<>::Init()
    @     0x7f4bbc8d449a  caffe::Solver<>::Solver()
    @     0x7f4bbc8f3513  caffe::Creator_SGDSolver<>()
    @           0x40ab99  train()
    @           0x4074a8  main
    @     0x7f4bbac53830  __libc_start_main
    @           0x407eb9  _start
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by khalilo** [comment]
@MhLiao Is there a solution for this problem ? Thanks.

**Comment by MhLiao** [comment]
@khalilo There may be some mistakes in your lmdb, according to your error information.

**Comment by 19931991** [comment]
Do you haved solved the problem? I meet it , and can you tell me the method ? Thank you very much !
My data of lmdb is : 
https://user-images.githubusercontent.com/28551961/34596646-777aa552-f21c-11e7-9e98-2135494da07a.png
and my train data is 73 bytes, test data is 69 bytes , my data is from icdar2013.

 this is my data path setting in the train.py : 
https://user-images.githubusercontent.com/28551961/34596662-99eb7076-f21c-11e7-913c-5b46c01ef361.png
https://user-images.githubusercontent.com/28551961/34596699-e0a9cd50-f21c-11e7-8e86-2c8a0897d40b.png

and this is my path setting in train.prototxt :and test.prototxt :

https://user-images.githubusercontent.com/28551961/34596713-fd1c0278-f21c-11e7-9f23-d4a9620bf2a2.png
https://user-images.githubusercontent.com/28551961/34596722-07c8caee-f21d-11e7-8bcb-551f8081bcc9.png
https://user-images.githubusercontent.com/28551961/34596733-169474d8-f21d-11e7-843f-fa11d5809cef.png

and my error is :

https://user-images.githubusercontent.com/28551961/34596838-e0f32ff8-f21d-11e7-814f-ede2e90ae913.png

Looking forward to your reply! Thank you very much @khalilo

**Comment by 19931991** [comment]
Do you haved solved the problem? I meet it , and can you tell me the method ? Thank you very much !
My data of lmdb is :
![image](https://user-images.githubusercontent.com/28551961/34597214-548cba22-f220-11e7-9192-333e9251fb92.png)

and my train data is 73 bytes, test data is 69 bytes , my data is from icdar2013.

and this is my data path setting in the train.py :
![image](https://user-images.githubusercontent.com/28551961/34597223-6741a2cc-f220-11e7-90ad-6edecdbb6b7e.png)

![image](https://user-images.githubusercontent.com/28551961/34597227-6c317b86-f220-11e7-9e94-402a8d1ba64e.png)

and this is my path setting in train.prototxt :and test.prototxt :

![image](https://user-images.githubusercontent.com/28551961/34597235-783f8e22-f220-11e7-8268-ba42a2b6c06f.png)

![image](https://user-images.githubusercontent.com/28551961/34597255-9e78444e-f220-11e7-91fb-d7498c2f1d5c.png)

![image](https://user-images.githubusercontent.com/28551961/34597263-a44acbc6-f220-11e7-8550-1d0da6c7ea87.png)

and my error is :

![image](https://user-images.githubusercontent.com/28551961/34597269-b1d9461e-f220-11e7-8306-f22b6e0b5d6f.png)
Looking forward to your reply! Thank you very much @khalilo

**Comment by 19931991** [comment]
@MhLiao

**Comment by hsweif** [comment]
@19931991 Have you solved this problem? I faced same issue, too. Please tell me the solution if you found it. Thank you.

**Comment by MeisonP** [comment]
please check the path of lmdb data. @19931991
