### ISSUE TITLE
Error in trainning upon changing the aspect ratios

### ISSUE THREAD

**Issue by Yash5595** [MhLiao/TextBoxes#31]
Hi !
I was experimenting with the parameters and thought of changing the aspect ratios from [2,3,5,7,10] to [1,2,3,5,7] and got this error while training :

F0615 09:42:51.943936 18711 multibox_loss_layer.cpp:143] Check failed: num_priors_ * loc_classes_ * 4 == bottom[0]->channels() (224088 vs. 266728) Number of priors must match number of location predictions.

I am getting the same error if I try to add any other integer to [2,3,5,7,10].
Can you please help me to resort this issue.
Thanks in advance!

**Comment by MhLiao** [comment]
@Yash5595 
You need to remove "1" because "1" will be added by default in the prior_box_layer.
