### ISSUE TITLE
"clip" parameter in PriorBoxLayer

### ISSUE THREAD

**Issue by U019TT** [MhLiao/TextBoxes#32]
Hi, @MhLiao 
I found that you set the parameter 'clip' to 'true' in your train script.
Could you please explain why did you do this? 
Does this parameter have effect on performance?
Thanks a lot.

**Comment by MhLiao** [comment]
@enmengyi 
'clip' is set to make sure all default boxes are within the image.

**Comment by U019TT** [comment]
@MhLiao 
I found this option is set to 'False' in the script of SSD. My question is whether 'clip' will impact on the detection accuracy. Or maybe the difficulty of training will decrease when 'clip' is set?

**Comment by MhLiao** [comment]
@enmengyi There are some default boxes which would be out of the image because I added default boxes with vertical offsets.  I am not sure whether the 'clip' has an effect on performance but I guess it does little matter.

**Comment by U019TT** [comment]
@MhLiao Thanks for your timely response!
