### ISSUE TITLE
cannot find -lopencv_dep_cudart

### ISSUE THREAD

**Issue by tsangsea** [MhLiao/TextBoxes#33]
每次都遇到这个问题说找不到，要吐血了，请求支援

**Comment by MhLiao** [comment]
what's your version of opencv?

**Comment by tsangsea** [comment]
用的opencv 2.4.12, 另外在另一台机器安装编译过了不过老出现：
/TextBoxes/examples/TextBoxes$ python test_icdar13.py
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0527 19:02:48.273658 10427 common.cpp:66] Cannot use GPU in CPU-only Caffe: check mode.
*** Check failure stack trace: ***
已放弃 (核心已转储)

**Comment by zhongxingli** [comment]
check out Makefile.config to see whether cpu_only is commented
and then make clean remake
if not solved

**Comment by tsangsea** [comment]
知道原因了，ROOT_caffe目录就是TextBoxes住目录，我勒个去
