### ISSUE TITLE
What's the meaning of detection_eval?

### ISSUE THREAD

**Issue by U019TT** [MhLiao/TextBoxes#35]
Hi, @MhLiao 
In the training phase, I saw the test net outputting "detection_eval = ***". What's meaning of this value? I wonder whether I can judge the network's performance in terms of this value. 
Thanks!
(I found this value isn't equal to the actual F-measure.)

**Comment by MhLiao** [comment]
@enmengyi It is an average precision. The f-measure is different with different thresholds, which is not convenient to evaluate the performance of models in the training period.
