### ISSUE TITLE
Time consumption

### ISSUE THREAD

**Issue by zacniewski** [MhLiao/TextBoxes#37]
@MhLiao, in your article in table 1 time consumption for few methods is presented. How did you measure these times? My GPU is weaker than Titan X and I'd like to get to know times on my machine. Of course, I'm particularly interested in your method and I assume that I should add some tic tac in test_icdar13.py file, but I'd like to know your opinion.

Best regards

**Comment by MhLiao** [comment]
You can add timer in test_icdar13.py file and average the time.

**Comment by ahmedmazari-dhatim** [comment]
@zacniewski ,
what is the capacity, the memory of the TITAN X GPU ?
