### ISSUE TITLE
Can not make

### ISSUE THREAD

**Issue by camel007** [MhLiao/TextBoxes#40]
nd@nd-Z97X-UD3H:~/yao/TextBoxes$ make -j8  
CXX src/caffe/data_transformer.cpp  
CXX src/caffe/util/sampler.cpp  
CXX src/caffe/util/upgrade_proto.cpp  
CXX src/caffe/util/bbox_util.cpp  
CXX src/caffe/util/im2col.cpp  
CXX src/caffe/util/im_transforms.cpp  
CXX src/caffe/util/blocking_queue.cpp  
CXX src/caffe/util/db.cpp  
CXX src/caffe/util/io.cpp  
CXX src/caffe/util/insert_splits.cpp  
In file included from src/caffe/util/im_transforms.cpp:20:0:
./include/caffe/util/im_transforms.hpp:44:37: error: ‘ResizeParameter’ does not name a type
 void UpdateBBoxByResizePolicy(const ResizeParameter& param,
                                     ^
./include/caffe/util/im_transforms.hpp:46:31: error: ‘NormalizedBBox’ has not been declared
                               NormalizedBBox* bbox);
                               ^
./include/caffe/util/im_transforms.hpp:48:50: error: ‘ResizeParameter’ does not name a type
 cv::Mat ApplyResize(const cv::Mat& in_img, const ResizeParameter& param);
                                                  ^
./include/caffe/util/im_transforms.hpp:50:49: error: ‘NoiseParameter’ does not name a type
 cv::Mat ApplyNoise(const cv::Mat& in_img, const NoiseParameter& param);
                                                 ^
src/caffe/util/im_transforms.cpp:251:37: error: ‘ResizeParameter’ does not name a type
 void UpdateBBoxByResizePolicy(const ResizeParameter& param  
.
.
.
make: *** [.build_release/src/caffe/util/upgrade_proto.o] Error 1
^Cmake: *** [.build_release/src/caffe/util/io.o] Interrupt
make: *** [.build_release/src/caffe/data_transformer.o] Interrupt
make: *** [.build_release/src/caffe/util/sampler.o] Interrupt
make: *** [.build_release/src/caffe/util/blocking_queue.o] Interrupt
make: *** [.build_release/src/caffe/util/insert_splits.o] Interrupt
make: *** wait: No child processes.  Stop.

Then I add caffe.pb.h in 'include/caffe/proto/', This error still appear.

**Comment by lomograb** [comment]
What OpenCV version you're using ?

**Comment by Kongsea** [comment]
Encountered the same error...
Could you please tell me how you solved the problem? Thank you.
