### ISSUE TITLE
Is textBoxes adapted to document images like scanned invoices ? 

### ISSUE THREAD

**Issue by ahmedmazari-dhatim** [MhLiao/TextBoxes#42]
Hello,
Let me first thank you for this excellent work.

l'm wondering if TextBoxes can be applied to document images or just for natural images. 

![invoice](https://user-images.githubusercontent.com/26280625/27857671-e13cf85e-6172-11e7-81dd-c2fe5d1dfd2e.jpg)

Thanks a lot

**Comment by lomograb** [comment]
I have tried this script to detect texts on an identity card and the accuracy is above 97% accurate

**Comment by ahmedmazari-dhatim** [comment]
Hi @lomograb , really ! excellent results.
1)Have you trained the model from scratch with your own data or you applied transfer learning (fine tuning)  the pretrained model ?
2) What is the dataset (identity card) you used to get 97% ?
3) Do you mind sharing  your code with us ?

l would be  very grateful. All your comments and answers are welcome.

Thank you
Ahmed

**Comment by tobechao** [comment]
@lomograb Hi, i want to ask about how to implement, Thank you?
