### ISSUE TITLE
TextBoxes_icdar13.caffemodel problem

### ISSUE THREAD

**Issue by naivepark** [MhLiao/TextBoxes#44]
Hi MhLiao
I download the codes and ready to run your code.
But i dont know where can i find this file -> [TextBoxes_icdar13.caffemodel]
Where can i find this file?
Thanks

**Comment by MhLiao** [comment]
@naivepark The link is on the readme page.

**Comment by naivepark** [comment]
It was simple problem!
Thanks!!!
