### ISSUE TITLE
Demo.py predicts only 5 words out 500 words, why ?

### ISSUE THREAD

**Issue by ahmedmazari-dhatim** [MhLiao/TextBoxes#46]
Hello,

l run demo.py on an invoice image l got the following   : 
![demo_result2](https://user-images.githubusercontent.com/26280625/28026906-b5278c38-6597-11e7-903e-43119ddf05af.jpg)

Why the Netwok is not able to predict all the words ?

Thank you

**Comment by MhLiao** [comment]
@ahmedmazari-dhatim Maybe they are too small. You can expand the input image for better results.
