### ISSUE TITLE
ImportError: No module named shapely

### ISSUE THREAD

**Issue by tlatlbtle** [MhLiao/TextBoxes#47]
I have followed your guide and when I run
`python demo.py`
Error occurs, error message shows as follow:
```
Traceback (most recent call last):
  File "demo.py", line 8, in <module>
    from nms import nms
  File "/home/wangjianbo_i/TextBoxes/examples/TextBoxes/nms.py", line 3, in <module>
    import shapely
ImportError: No module named shapely
```

Also, in your guide, 
```
Test
run "python examples/demo.py".
```
May should be 
`python examples/TextBoxes/demo.py`

**Comment by yangnk** [comment]
I also encountered the same problem, how do you solve?

**Comment by yangnk** [comment]
@wjbKimberly I also encountered the same problem, how do you solve?

**Comment by tlatlbtle** [comment]
Run
`pip install shapely`

**Comment by Liampingfang** [comment]
Due to my computer can not surf the internet,so how to solve the problem?

**Comment by alberto-alde** [comment]
buen dia wjbKimberly tengo un problema "No module named shapely ", estoy tratando de instalar un modulo para odoo, ya instale postgis agregue extensiones, instale shapely en python asi como geojson , estos son los modulos de requisito, pero no se si tengo que hacer algo mas para que funcione.

**Comment by arkothiwala** [comment]
https://gis.stackexchange.com/questions/62925/shapely-not-installing-correctly will solve the problem
