### ISSUE TITLE
difference between TextBoxes and SSD

### ISSUE THREAD

**Issue by zjuDebug** [MhLiao/TextBoxes#5]
What is the difference of TextBoxes and SSD? Is it just modify the default boxes?

**Comment by MhLiao** [comment]
@zjuDebug The default boxes and the convolutional kernel sizes for prediction.

**Comment by zjuDebug** [comment]
@MhLiao Thanks a lot! Meanwhile, what's the difference between TextBoxes and SSD when training?

**Comment by MhLiao** [comment]
@zjuDebug You'd better refer to the paper for training details.

**Comment by zjuDebug** [comment]
@MhLiao Thanks a lot!

**Comment by beyondli** [comment]
@MhLiao ,I read code of ssd and textbox ,beside the box and some kernel parameters .some kernel code seems revised. The most change is in MultiBoxLossLayer::Forward, the MineHardExamples has been deleted, and replaced by calcuate the class scores with loss fun and overlap of box,seems you think origanal code is not vary efficent or some basic kernel idea need update?? I think..
