### ISSUE TITLE
Query about icdar_2013.caffemodel

### ISSUE THREAD

**Issue by rayush7** [MhLiao/TextBoxes#50]
Hi @MhLiao 

Could you please clarify that the model icdar_2013.caffemodel is pretrained on SynthText dataset and then trained on ICDAR 2013 Text localization dataset (as mentioned in the paper) or it is only trained on ICDAR 2013 Text localization dataset?

**Comment by MhLiao** [comment]
It is pre-trained on SynthText dataset and then trained on ICDAR 2013 Text localization data set.

**Comment by rayush7** [comment]
Alright thanks @MhLiao
