### ISSUE TITLE
AttributeError: 'module' object has no attribute 'ResizeParameter'

### ISSUE THREAD

**Issue by InesBeltaief** [MhLiao/TextBoxes#57]
trying to run  python train_icdar13.py , I got the error
`Traceback (most recent call last):
  File "train_icdar13.py", line 155, in <module>
    'resize_mode': P.Resize.WARP,
  File "/home/ines/caffe/python/caffe/net_spec.py", line 280, in __getattr__
    return getattr(getattr(caffe_pb2, name + 'Parameter'), param_name)
**AttributeError: 'module' object has no attribute 'ResizeParameter'**
`

**Comment by MhLiao** [comment]
You use the wrong Caffe path "/home/ines/caffe/", which seems to be your own Caffe root. You should use the Caffe in this repository.

**Comment by InesBeltaief** [comment]
@MhLiao thanks for replying !
