### ISSUE TITLE
How to use SynthText for training?

### ISSUE THREAD

**Issue by lufo816** [MhLiao/TextBoxes#6]
Text in SynthText is oriented and its label has 4 points, how to use these data for training?

**Comment by MhLiao** [comment]
@lufo816 use the maximum rectangle(xmin,ymin,xmax,ymax) as the bounding box

**Comment by lufo816** [comment]
@MhLiao Understood, thanks a lot!

**Comment by vrbala** [comment]
@MhLiao I am trying to use SynthText to fine tune the model. However, I am not sure how to preprocess the data such that it is suitable to use with TextBoxes. Specifically, I couldn't figure out the schema of data in lmdb files. Could you kindly point me at some relevant references? Thanks in advance.

**Comment by MhLiao** [comment]
@vrbala The schema of data in lmdb files is similar to the SSD. You can use the scripts of SSD to generate the lmdb data.

**Comment by vrbala** [comment]
@MhLiao Thanks so much.

**Comment by HelloTobe** [comment]
@MhLiao   Hi, the SynthText datas are in decimal form, should i use the round function to make them into integers?
What pictures in SynthText did you use for training, validation or testing respectively?  (I mean i don't know what pictures should be categorized into training, also is validation and testing.) 
Thanks in advance.

**Comment by MhLiao** [comment]
@HelloTobe yes. I used 800k images for training, 58750 images for validation.

**Comment by HelloTobe** [comment]
Thanks for your reply!
By the way, i'm wondering how long you finish your training.

**Comment by HelloTobe** [comment]
@MhLiao Hi, thanks for your reply!

Another problem is that some bounding boxes  exceed image boundary(some coordinates are too large or negative), could you give me some adviece to solve this problem?

By the way, i'm wondering how long you finish your training.

**Comment by lomograb** [comment]
@HelloTobe You can enable CUDA or cuDNN (GPU MODE) for quick result of training time

**Comment by offlaner** [comment]
@MhLiao @lufo816 For training on synthText are we supposed to generate txt files in the form of : 
xmin ymin xmax ymax "text"
instead of : 
Xcentre Ycentre w h "text"

**Comment by zhongxingli** [comment]
@offlaner 
hello
can you share how the training format in *.txt is 
for finetune,which can  run train_icdar2013.py ;
but the dataset needs to prepare;
can you explain how to prepare your own data in detail
if so, much efforts would be very appreciated.
thk by advance.

**Comment by github14343** [comment]
@HelloTobe  Have you solved the problem " bounding box exceeds image boundary." Thanks for help

**Comment by HelloTobe** [comment]
@github14343  I probably just clip the coordinate `x` such that `0 <= x <= H (or W)`.

**Comment by github14343** [comment]
> @github14343 I probably just clip the coordinate `x` such that `0 <= x <= H (or W)`.

Thanks!

**Comment by github14343** [comment]
@HelloTobe  Thanks!
