### ISSUE TITLE
Questions on detection outputs.

### ISSUE THREAD

**Issue by y2e4hfg** [MhLiao/TextBoxes#60]
Hi, i am new to this and would like to ask what should be the detection output of the train_icdar13.py code as i think the detection result should be stored on the output_result_dir but there isn't anything there after the training (It says Optimization Done). Another question is how do i obtain the fmeasure, recall and precision of the code? Thanks.

**Comment by MhLiao** [comment]
You can use test_icdar13.py to get the detection outputs and follow the evaluation_nms.m to get the f-measure, recall, and precision.

**Comment by y2e4hfg** [comment]
Thanks for your prompt reply! I have solved the problem of getting the f-measure, recall, and precision.
Another question is why do i get this in my train_icdar13.py training?

I0803 12:39:23.866760  3423 net.cpp:693] Ignoring source layer mbox_loss
I0803 12:39:46.088191  3423 detection_output_layer.cu:123] Couldn't find any detections
I0803 12:39:47.131496  3423 solver.cpp:531]     Test net output #0: detection_eval = 0
I0803 12:39:47.131533  3423 solver.cpp:325] Optimization Done.
I0803 12:39:47.131537  3423 caffe.cpp:254] Optimization Done.

It says optimization done but i don't have any output on my output directory.
