### ISSUE TITLE
training data format

### ISSUE THREAD

**Issue by ck-dachui** [MhLiao/TextBoxes#63]
I download icdar2013 and read train_icdar2013.py
but till now do not have the idea how was the training format is
icdar2013 dataset i dave, but how to prepare that data
thk for the kind by advance.

**Comment by MhLiao** [comment]
I give the reference "xml" format in "readme.md". Once you generate the "xml" files, you can follow the scripts in SSD to generate "LMDB data" for training.

**Comment by zhongxingli** [comment]
@MhLiao 如果要进行端到端的微调，用您给的train_cidar2013.py应该是可以训练了吧
前提转好xml的数据格式；
看train.icdar2013.py内容，里面有train/val1/val2/test这些txt文件格式在内，在这不清楚这些txt中到底都包含些什么，如ssd中trainval.txt只有没有后缀的图片名，如果用上面.py进行训练的话好像是有问题。

**Comment by MhLiao** [comment]
你需要先生成xml文件和对应的list(类似trainval.txt)，然后使用SSD的create_data.sh脚本生成lmdb数据，使用lmdb数据训练。

**Comment by zhongxingli** [comment]
训练时不需要直接运行给的train_icdar2013.py么
还是使用build/tools/caffe train这种
如果是后者是不是就是直接按照ssd格式就可以训练然后测试了

**Comment by MhLiao** [comment]
运行train_icdar2013.py进行训练。在train_icdar2013.py里面提供lmdb的路径即可。

**Comment by zhongxingli** [comment]
。。。
train_icdar2013.py中有些默认的train/val1/val2/test.txt文本文件
这些有用么，还是说trainval/test中分别保存对应的训练测试数据，然后val1/val2将trainval中list七三分

**Comment by zhongxingli** [comment]
原本打算放在别的帖子下，想一下还是放在了这边。
@MhLiao 看issues,里面很多都有关于数据准备问题
作为作者觉得很简单正常
最近几天都在看create_data.sh/create_annoset.py/train_icdar2013.py依然没有太把握主线
推出的对应xml格式很简单，生成lmdb用train_icdar.py直接训练就好
问题是lmdb的生成，里面涉及train.txt数据格式问题
如图片名字和对应xml要写在一行
如windows转的trainval.txt直接放到ubuntu中会因为末尾\r\n问题，line.stripe('\n').split(' ')会一直出现问题
所以楼主可否稍加详细，作为私人代码这样要求就太过了
楼主好心开源，那就能不能好人做到底
关于数据准备转lmdb等稍花时间相对详细说一下呢
因为总体来说，数据格式问题解决了，就剩下train_icdar2013.py这类问题或者换VGG或PVANET等问题了
感谢。
