### ISSUE TITLE
The test Result of TextBoxes on ICDAR2013

### ISSUE THREAD

**Issue by athmey** [MhLiao/TextBoxes#64]
Hi Mr.Liao,

Thank you so much for providing such wonderful code for us to learn.

I have run the demo following the instructions you provided. Due to the GPU limit(GTX 1080), I only comment the (1600*1600) input size in the demo.py. The other places keep the same as origin.

However the test result makes me confused. 
![test_img_1](https://user-images.githubusercontent.com/29476966/29261709-8d7b331a-8103-11e7-8972-6e3ec5d070ab.jpg)
![test_img_2](https://user-images.githubusercontent.com/29476966/29261710-8d7f4f22-8103-11e7-81f6-faf8a3b69e19.jpg)

Since TextBoxes is really strong due to the result shown in your paper,maybe I need to modify some essential paramters. I am waiting for your reply sincerely.

Thank you so much!

**Comment by MhLiao** [comment]
Did you use the given model?

**Comment by athmey** [comment]
sure, I use the model directly downloaded from the BAIDUYUN link:

TextBoxes_icdar13.caffemodel

**Comment by athmey** [comment]
`import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import os
import xml.dom.minidom
# %matplotlib inline
from nms import nms
plt.rcParams['figure.figsize'] = (10, 10)
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'

# Make sure that caffe is on the python path:
caffe_root = './'  # this file is expected to be in {caffe_root}/examples
os.chdir(caffe_root)
import sys
sys.path.insert(0, 'python')

import caffe
caffe.set_device(0)
caffe.set_mode_gpu()

model_def = './examples/TextBoxes/deploy.prototxt'
model_weights = './examples/TextBoxes/TextBoxes_icdar13.caffemodel'

#origin of this flag is True, for my own situation,since the gpu can not hold the "use_multi_scale" switch,i set this flag to false
use_multi_scale = True

if not use_multi_scale:
	scales=((700,700),)
else:
	#scales=((300,300),(700,700),(700,500),(700,300),(1600,1600))
	scales=((300,300),(700,700),(700,500),(700,300))

net = caffe.Net(model_def,      # defines the structure of the model
                model_weights,  # contains the trained weights
                caffe.TEST)     # use test mode (e.g., don't perform dropout)

dt_results=[]

#image_path='./examples/img/demo.jpg'
image_folder='./examples/img/'
image_list = os.listdir(image_folder)
image_dest_folder='./examples/results/'

conf_thresh = 1.00

for image in image_list:
    try:
		image_name = str(image)
		print(image_name)
	
		image_path = image_folder + image_name
		image=caffe.io.load_image(image_path)

		image_height,image_width,channels=image.shape
		plt.clf()
		plt.imshow(image)
		currentAxis = plt.gca()

		for scale in scales:
			print(scale)
			image_resize_height = scale[0]
			image_resize_width = scale[1]
			transformer = caffe.io.Transformer({'data': (1,3,image_resize_height,image_resize_width)})
			transformer.set_transpose('data', (2, 0, 1))
			transformer.set_mean('data', np.array([104,117,123])) # mean pixel
			transformer.set_raw_scale('data', 255)  # the reference model operates on images in [0,255] range instead of [0,1]
			transformer.set_channel_swap('data', (2,1,0))  # the reference model has channels in BGR order instead of RGB

			net.blobs['data'].reshape(1,3,image_resize_height,image_resize_width)
			transformed_image = transformer.preprocess('data', image)
			net.blobs['data'].data[...] = transformed_image
			# Forward pass.
			detections = net.forward()['detection_out']
			# Parse the outputs.
			det_label = detections[0,0,:,1]
			det_conf = detections[0,0,:,2]
			det_xmin = detections[0,0,:,3]
			det_ymin = detections[0,0,:,4]
			det_xmax = detections[0,0,:,5]
			det_ymax = detections[0,0,:,6]
			top_indices = [i for i, conf in enumerate(det_conf) if conf >= conf_thresh]
			top_conf = det_conf[top_indices]
			top_xmin = det_xmin[top_indices]
			top_ymin = det_ymin[top_indices]
			top_xmax = det_xmax[top_indices]
			top_ymax = det_ymax[top_indices]

			for i in xrange(top_conf.shape[0]):
				xmin = int(round(top_xmin[i] * image.shape[1]))
				ymin = int(round(top_ymin[i] * image.shape[0]))
				xmax = int(round(top_xmax[i] * image.shape[1]))
				ymax = int(round(top_ymax[i] * image.shape[0]))
				xmin = max(1,xmin)
				ymin = max(1,ymin)
				xmax = min(image.shape[1]-1, xmax)
				ymax = min(image.shape[0]-1, ymax)
				score = top_conf[i]
				dt_result=[xmin,ymin,xmax,ymin,xmax,ymax,xmin,ymax,score]
				dt_results.append(dt_result)




		dt_results = sorted(dt_results, key=lambda x:-float(x[8]))
		nms_flag = nms(dt_results,0.3)

		for k,dt in enumerate(dt_results):
			  if nms_flag[k]:
				name = '%.2f'%(dt[8])
				xmin = dt[0]
				ymin = dt[1]
				xmax = dt[2]
				ymax = dt[5]
				coords = (xmin, ymin), xmax-xmin+1, ymax-ymin+1
				color = 'b'
				currentAxis.add_patch(plt.Rectangle(*coords, fill=False, edgecolor=color, linewidth=2))
				currentAxis.text(xmin, ymin, name, bbox={'facecolor':'white', 'alpha':0.5})

		#plt.savefig('./examples/results/demo_result.jpg')
		dest_img_path = image_dest_folder + image_name
		plt.savefig(str(dest_img_path))
    except Exception as e:
		print("Exception Occurs")
		continue

print('success')

`

Above code is the "demo.py" that I used

**Comment by athmey** [comment]
``import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import os
import xml.dom.minidom
# %matplotlib inline
from nms import nms
plt.rcParams['figure.figsize'] = (10, 10)
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'

# Make sure that caffe is on the python path:
caffe_root = './'  # this file is expected to be in {caffe_root}/examples
os.chdir(caffe_root)
import sys
sys.path.insert(0, 'python')

import caffe
caffe.set_device(0)
caffe.set_mode_gpu()

model_def = './examples/TextBoxes/deploy.prototxt'
model_weights = './examples/TextBoxes/TextBoxes_icdar13.caffemodel'

#origin of this flag is True, for my own situation,since the gpu can not hold the "use_multi_scale" switch,i set this flag to false
use_multi_scale = True

if not use_multi_scale:
	scales=((700,700),)
else:
	#scales=((300,300),(700,700),(700,500),(700,300),(1600,1600))
	scales=((300,300),(700,700),(700,500),(700,300))

net = caffe.Net(model_def,      # defines the structure of the model
                model_weights,  # contains the trained weights
                caffe.TEST)     # use test mode (e.g., don't perform dropout)

dt_results=[]

#image_path='./examples/img/demo.jpg'
image_folder='./examples/img/'
image_list = os.listdir(image_folder)
image_dest_folder='./examples/results/'

conf_thresh = 1.00

for image in image_list:
    try:
		image_name = str(image)
		print(image_name)
	
		image_path = image_folder + image_name
		image=caffe.io.load_image(image_path)

		image_height,image_width,channels=image.shape
		plt.clf()
		plt.imshow(image)
		currentAxis = plt.gca()

		for scale in scales:
			print(scale)
			image_resize_height = scale[0]
			image_resize_width = scale[1]
			transformer = caffe.io.Transformer({'data': (1,3,image_resize_height,image_resize_width)})
			transformer.set_transpose('data', (2, 0, 1))
			transformer.set_mean('data', np.array([104,117,123])) # mean pixel
			transformer.set_raw_scale('data', 255)  # the reference model operates on images in [0,255] range instead of [0,1]
			transformer.set_channel_swap('data', (2,1,0))  # the reference model has channels in BGR order instead of RGB

			net.blobs['data'].reshape(1,3,image_resize_height,image_resize_width)
			transformed_image = transformer.preprocess('data', image)
			net.blobs['data'].data[...] = transformed_image
			# Forward pass.
			detections = net.forward()['detection_out']
			# Parse the outputs.
			det_label = detections[0,0,:,1]
			det_conf = detections[0,0,:,2]
			det_xmin = detections[0,0,:,3]
			det_ymin = detections[0,0,:,4]
			det_xmax = detections[0,0,:,5]
			det_ymax = detections[0,0,:,6]
			top_indices = [i for i, conf in enumerate(det_conf) if conf >= conf_thresh]
			top_conf = det_conf[top_indices]
			top_xmin = det_xmin[top_indices]
			top_ymin = det_ymin[top_indices]
			top_xmax = det_xmax[top_indices]
			top_ymax = det_ymax[top_indices]

			for i in xrange(top_conf.shape[0]):
				xmin = int(round(top_xmin[i] * image.shape[1]))
				ymin = int(round(top_ymin[i] * image.shape[0]))
				xmax = int(round(top_xmax[i] * image.shape[1]))
				ymax = int(round(top_ymax[i] * image.shape[0]))
				xmin = max(1,xmin)
				ymin = max(1,ymin)
				xmax = min(image.shape[1]-1, xmax)
				ymax = min(image.shape[0]-1, ymax)
				score = top_conf[i]
				dt_result=[xmin,ymin,xmax,ymin,xmax,ymax,xmin,ymax,score]
				dt_results.append(dt_result)




		dt_results = sorted(dt_results, key=lambda x:-float(x[8]))
		nms_flag = nms(dt_results,0.3)

		for k,dt in enumerate(dt_results):
			  if nms_flag[k]:
				name = '%.2f'%(dt[8])
				xmin = dt[0]
				ymin = dt[1]
				xmax = dt[2]
				ymax = dt[5]
				coords = (xmin, ymin), xmax-xmin+1, ymax-ymin+1
				color = 'b'
				currentAxis.add_patch(plt.Rectangle(*coords, fill=False, edgecolor=color, linewidth=2))
				currentAxis.text(xmin, ymin, name, bbox={'facecolor':'white', 'alpha':0.5})

		#plt.savefig('./examples/results/demo_result.jpg')
		dest_img_path = image_dest_folder + image_name
		plt.savefig(str(dest_img_path))
    except Exception as e:
		print("Exception Occurs")
		continue

print('success')

**Comment by athmey** [comment]
``
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import os
import xml.dom.minidom
# %matplotlib inline
from nms import nms
plt.rcParams['figure.figsize'] = (10, 10)
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'

# Make sure that caffe is on the python path:
caffe_root = './'  # this file is expected to be in {caffe_root}/examples
os.chdir(caffe_root)
import sys
sys.path.insert(0, 'python')

import caffe
caffe.set_device(0)
caffe.set_mode_gpu()

model_def = './examples/TextBoxes/deploy.prototxt'
model_weights = './examples/TextBoxes/TextBoxes_icdar13.caffemodel'

#origin of this flag is True, for my own situation,since the gpu can not hold the "use_multi_scale" switch,i set this flag to false
use_multi_scale = True

if not use_multi_scale:
	scales=((700,700),)
else:
	#scales=((300,300),(700,700),(700,500),(700,300),(1600,1600))
	scales=((300,300),(700,700),(700,500),(700,300))

net = caffe.Net(model_def,      # defines the structure of the model
                model_weights,  # contains the trained weights
                caffe.TEST)     # use test mode (e.g., don't perform dropout)

dt_results=[]

#image_path='./examples/img/demo.jpg'
image_folder='./examples/img/'
image_list = os.listdir(image_folder)
image_dest_folder='./examples/results/'

conf_thresh = 1.00

for image in image_list:
    try:
		image_name = str(image)
		print(image_name)
	
		image_path = image_folder + image_name
		image=caffe.io.load_image(image_path)

		image_height,image_width,channels=image.shape
		plt.clf()
		plt.imshow(image)
		currentAxis = plt.gca()

		for scale in scales:
			print(scale)
			image_resize_height = scale[0]
			image_resize_width = scale[1]
			transformer = caffe.io.Transformer({'data': (1,3,image_resize_height,image_resize_width)})
			transformer.set_transpose('data', (2, 0, 1))
			transformer.set_mean('data', np.array([104,117,123])) # mean pixel
			transformer.set_raw_scale('data', 255)  # the reference model operates on images in [0,255] range instead of [0,1]
			transformer.set_channel_swap('data', (2,1,0))  # the reference model has channels in BGR order instead of RGB

			net.blobs['data'].reshape(1,3,image_resize_height,image_resize_width)
			transformed_image = transformer.preprocess('data', image)
			net.blobs['data'].data[...] = transformed_image
			# Forward pass.
			detections = net.forward()['detection_out']
			# Parse the outputs.
			det_label = detections[0,0,:,1]
			det_conf = detections[0,0,:,2]
			det_xmin = detections[0,0,:,3]
			det_ymin = detections[0,0,:,4]
			det_xmax = detections[0,0,:,5]
			det_ymax = detections[0,0,:,6]
			top_indices = [i for i, conf in enumerate(det_conf) if conf >= conf_thresh]
			top_conf = det_conf[top_indices]
			top_xmin = det_xmin[top_indices]
			top_ymin = det_ymin[top_indices]
			top_xmax = det_xmax[top_indices]
			top_ymax = det_ymax[top_indices]

			for i in xrange(top_conf.shape[0]):
				xmin = int(round(top_xmin[i] * image.shape[1]))
				ymin = int(round(top_ymin[i] * image.shape[0]))
				xmax = int(round(top_xmax[i] * image.shape[1]))
				ymax = int(round(top_ymax[i] * image.shape[0]))
				xmin = max(1,xmin)
				ymin = max(1,ymin)
				xmax = min(image.shape[1]-1, xmax)
				ymax = min(image.shape[0]-1, ymax)
				score = top_conf[i]
				dt_result=[xmin,ymin,xmax,ymin,xmax,ymax,xmin,ymax,score]
				dt_results.append(dt_result)




		dt_results = sorted(dt_results, key=lambda x:-float(x[8]))
		nms_flag = nms(dt_results,0.3)

		for k,dt in enumerate(dt_results):
			  if nms_flag[k]:
				name = '%.2f'%(dt[8])
				xmin = dt[0]
				ymin = dt[1]
				xmax = dt[2]
				ymax = dt[5]
				coords = (xmin, ymin), xmax-xmin+1, ymax-ymin+1
				color = 'b'
				currentAxis.add_patch(plt.Rectangle(*coords, fill=False, edgecolor=color, linewidth=2))
				currentAxis.text(xmin, ymin, name, bbox={'facecolor':'white', 'alpha':0.5})

		#plt.savefig('./examples/results/demo_result.jpg')
		dest_img_path = image_dest_folder + image_name
		plt.savefig(str(dest_img_path))
    except Exception as e:
		print("Exception Occurs")
		continue

print('success')


``

**Comment by athmey** [comment]
[demo.txt](https://github.com/MhLiao/TextBoxes/files/1221799/demo.txt)

The code in the "demo.txt" is what I used in "demo.py"

**Comment by MhLiao** [comment]
@athmey I can not see your "demo.txt".

**Comment by athmey** [comment]
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import os
import xml.dom.minidom
# %matplotlib inline
from nms import nms
plt.rcParams['figure.figsize'] = (10, 10)
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'

# Make sure that caffe is on the python path:
caffe_root = './'  # this file is expected to be in {caffe_root}/examples
os.chdir(caffe_root)
import sys
sys.path.insert(0, 'python')

import caffe
caffe.set_device(0)
caffe.set_mode_gpu()

model_def = './examples/TextBoxes/deploy.prototxt'
model_weights = './examples/TextBoxes/TextBoxes_icdar13.caffemodel'

#origin of this flag is True, for my own situation,since the gpu can not hold the "use_multi_scale" switch,i set this flag to false
use_multi_scale = True

if not use_multi_scale:
	scales=((700,700),)
else:
	#scales=((300,300),(700,700),(700,500),(700,300),(1600,1600))
	scales=((300,300),(700,700),(700,500),(700,300))

net = caffe.Net(model_def,      # defines the structure of the model
                model_weights,  # contains the trained weights
                caffe.TEST)     # use test mode (e.g., don't perform dropout)

dt_results=[]

#image_path='./examples/img/demo.jpg'
image_folder='./examples/img/'
image_list = os.listdir(image_folder)
image_dest_folder='./examples/results/'

conf_thresh = 0.6

for image in image_list:
    try:
		image_name = str(image)
		print(image_name)
	
		image_path = image_folder + image_name
		image=caffe.io.load_image(image_path)

		image_height,image_width,channels=image.shape
		plt.clf()
		plt.imshow(image)
		currentAxis = plt.gca()

		for scale in scales:
			print(scale)
			image_resize_height = scale[0]
			image_resize_width = scale[1]
			transformer = caffe.io.Transformer({'data': (1,3,image_resize_height,image_resize_width)})
			transformer.set_transpose('data', (2, 0, 1))
			transformer.set_mean('data', np.array([104,117,123])) # mean pixel
			transformer.set_raw_scale('data', 255)  # the reference model operates on images in [0,255] range instead of [0,1]
			transformer.set_channel_swap('data', (2,1,0))  # the reference model has channels in BGR order instead of RGB

			net.blobs['data'].reshape(1,3,image_resize_height,image_resize_width)
			transformed_image = transformer.preprocess('data', image)
			net.blobs['data'].data[...] = transformed_image
			# Forward pass.
			detections = net.forward()['detection_out']
			# Parse the outputs.
			det_label = detections[0,0,:,1]
			det_conf = detections[0,0,:,2]
			det_xmin = detections[0,0,:,3]
			det_ymin = detections[0,0,:,4]
			det_xmax = detections[0,0,:,5]
			det_ymax = detections[0,0,:,6]
			top_indices = [i for i, conf in enumerate(det_conf) if conf >= conf_thresh]
			top_conf = det_conf[top_indices]
			top_xmin = det_xmin[top_indices]
			top_ymin = det_ymin[top_indices]
			top_xmax = det_xmax[top_indices]
			top_ymax = det_ymax[top_indices]

			for i in xrange(top_conf.shape[0]):
				xmin = int(round(top_xmin[i] * image.shape[1]))
				ymin = int(round(top_ymin[i] * image.shape[0]))
				xmax = int(round(top_xmax[i] * image.shape[1]))
				ymax = int(round(top_ymax[i] * image.shape[0]))
				xmin = max(1,xmin)
				ymin = max(1,ymin)
				xmax = min(image.shape[1]-1, xmax)
				ymax = min(image.shape[0]-1, ymax)
				score = top_conf[i]
				dt_result=[xmin,ymin,xmax,ymin,xmax,ymax,xmin,ymax,score]
				dt_results.append(dt_result)




		dt_results = sorted(dt_results, key=lambda x:-float(x[8]))
		nms_flag = nms(dt_results,0.3)

		for k,dt in enumerate(dt_results):
			  if nms_flag[k]:
				name = '%.2f'%(dt[8])
				xmin = dt[0]
				ymin = dt[1]
				xmax = dt[2]
				ymax = dt[5]
				coords = (xmin, ymin), xmax-xmin+1, ymax-ymin+1
				color = 'b'
				currentAxis.add_patch(plt.Rectangle(*coords, fill=False, edgecolor=color, linewidth=2))
				currentAxis.text(xmin, ymin, name, bbox={'facecolor':'white', 'alpha':0.5})

		#plt.savefig('./examples/results/demo_result.jpg')
		dest_img_path = image_dest_folder + image_name
		plt.savefig(str(dest_img_path))
    except Exception as e:
		print("Exception Occurs")
		continue

print('success')

**Comment by athmey** [comment]
`import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import os
import xml.dom.minidom
# %matplotlib inline
from nms import nms
plt.rcParams['figure.figsize'] = (10, 10)
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'

# Make sure that caffe is on the python path:
caffe_root = './'  # this file is expected to be in {caffe_root}/examples
os.chdir(caffe_root)
import sys
sys.path.insert(0, 'python')

import caffe
caffe.set_device(0)
caffe.set_mode_gpu()

model_def = './examples/TextBoxes/deploy.prototxt'
model_weights = './examples/TextBoxes/TextBoxes_icdar13.caffemodel'

#origin of this flag is True, for my own situation,since the gpu can not hold the "use_multi_scale" switch,i set this flag to false
use_multi_scale = True

if not use_multi_scale:
	scales=((700,700),)
else:
	#scales=((300,300),(700,700),(700,500),(700,300),(1600,1600))
	scales=((300,300),(700,700),(700,500),(700,300))

net = caffe.Net(model_def,      # defines the structure of the model
                model_weights,  # contains the trained weights
                caffe.TEST)     # use test mode (e.g., don't perform dropout)

dt_results=[]

#image_path='./examples/img/demo.jpg'
image_folder='./examples/img/'
image_list = os.listdir(image_folder)
image_dest_folder='./examples/results/'

conf_thresh = 0.6

for image in image_list:
    try:
		image_name = str(image)
		print(image_name)
	
		image_path = image_folder + image_name
		image=caffe.io.load_image(image_path)

		image_height,image_width,channels=image.shape
		plt.clf()
		plt.imshow(image)
		currentAxis = plt.gca()

		for scale in scales:
			print(scale)
			image_resize_height = scale[0]
			image_resize_width = scale[1]
			transformer = caffe.io.Transformer({'data': (1,3,image_resize_height,image_resize_width)})
			transformer.set_transpose('data', (2, 0, 1))
			transformer.set_mean('data', np.array([104,117,123])) # mean pixel
			transformer.set_raw_scale('data', 255)  # the reference model operates on images in [0,255] range instead of [0,1]
			transformer.set_channel_swap('data', (2,1,0))  # the reference model has channels in BGR order instead of RGB

			net.blobs['data'].reshape(1,3,image_resize_height,image_resize_width)
			transformed_image = transformer.preprocess('data', image)
			net.blobs['data'].data[...] = transformed_image
			# Forward pass.
			detections = net.forward()['detection_out']
			# Parse the outputs.
			det_label = detections[0,0,:,1]
			det_conf = detections[0,0,:,2]
			det_xmin = detections[0,0,:,3]
			det_ymin = detections[0,0,:,4]
			det_xmax = detections[0,0,:,5]
			det_ymax = detections[0,0,:,6]
			top_indices = [i for i, conf in enumerate(det_conf) if conf >= conf_thresh]
			top_conf = det_conf[top_indices]
			top_xmin = det_xmin[top_indices]
			top_ymin = det_ymin[top_indices]
			top_xmax = det_xmax[top_indices]
			top_ymax = det_ymax[top_indices]

			for i in xrange(top_conf.shape[0]):
				xmin = int(round(top_xmin[i] * image.shape[1]))
				ymin = int(round(top_ymin[i] * image.shape[0]))
				xmax = int(round(top_xmax[i] * image.shape[1]))
				ymax = int(round(top_ymax[i] * image.shape[0]))
				xmin = max(1,xmin)
				ymin = max(1,ymin)
				xmax = min(image.shape[1]-1, xmax)
				ymax = min(image.shape[0]-1, ymax)
				score = top_conf[i]
				dt_result=[xmin,ymin,xmax,ymin,xmax,ymax,xmin,ymax,score]
				dt_results.append(dt_result)




		dt_results = sorted(dt_results, key=lambda x:-float(x[8]))
		nms_flag = nms(dt_results,0.3)

		for k,dt in enumerate(dt_results):
			  if nms_flag[k]:
				name = '%.2f'%(dt[8])
				xmin = dt[0]
				ymin = dt[1]
				xmax = dt[2]
				ymax = dt[5]
				coords = (xmin, ymin), xmax-xmin+1, ymax-ymin+1
				color = 'b'
				currentAxis.add_patch(plt.Rectangle(*coords, fill=False, edgecolor=color, linewidth=2))
				currentAxis.text(xmin, ymin, name, bbox={'facecolor':'white', 'alpha':0.5})

		#plt.savefig('./examples/results/demo_result.jpg')
		dest_img_path = image_dest_folder + image_name
		plt.savefig(str(dest_img_path))
    except Exception as e:
		print("Exception Occurs")
		continue

print('success')
`

**Comment by athmey** [comment]
```
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import os
import xml.dom.minidom
# %matplotlib inline
from nms import nms
plt.rcParams['figure.figsize'] = (10, 10)
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'

# Make sure that caffe is on the python path:
caffe_root = './'  # this file is expected to be in {caffe_root}/examples
os.chdir(caffe_root)
import sys
sys.path.insert(0, 'python')

import caffe
caffe.set_device(0)
caffe.set_mode_gpu()

model_def = './examples/TextBoxes/deploy.prototxt'
model_weights = './examples/TextBoxes/TextBoxes_icdar13.caffemodel'

#origin of this flag is True, for my own situation,since the gpu can not hold the "use_multi_scale" switch,i set this flag to false
use_multi_scale = True

if not use_multi_scale:
	scales=((700,700),)
else:
	#scales=((300,300),(700,700),(700,500),(700,300),(1600,1600))
	scales=((300,300),(700,700),(700,500),(700,300))

net = caffe.Net(model_def,      # defines the structure of the model
                model_weights,  # contains the trained weights
                caffe.TEST)     # use test mode (e.g., don't perform dropout)

dt_results=[]

#image_path='./examples/img/demo.jpg'
image_folder='./examples/img/'
image_list = os.listdir(image_folder)
image_dest_folder='./examples/results/'

conf_thresh = 0.6

for image in image_list:
    try:
		image_name = str(image)
		print(image_name)
	
		image_path = image_folder + image_name
		image=caffe.io.load_image(image_path)

		image_height,image_width,channels=image.shape
		plt.clf()
		plt.imshow(image)
		currentAxis = plt.gca()

		for scale in scales:
			print(scale)
			image_resize_height = scale[0]
			image_resize_width = scale[1]
			transformer = caffe.io.Transformer({'data': (1,3,image_resize_height,image_resize_width)})
			transformer.set_transpose('data', (2, 0, 1))
			transformer.set_mean('data', np.array([104,117,123])) # mean pixel
			transformer.set_raw_scale('data', 255)  # the reference model operates on images in [0,255] range instead of [0,1]
			transformer.set_channel_swap('data', (2,1,0))  # the reference model has channels in BGR order instead of RGB

			net.blobs['data'].reshape(1,3,image_resize_height,image_resize_width)
			transformed_image = transformer.preprocess('data', image)
			net.blobs['data'].data[...] = transformed_image
			# Forward pass.
			detections = net.forward()['detection_out']
			# Parse the outputs.
			det_label = detections[0,0,:,1]
			det_conf = detections[0,0,:,2]
			det_xmin = detections[0,0,:,3]
			det_ymin = detections[0,0,:,4]
			det_xmax = detections[0,0,:,5]
			det_ymax = detections[0,0,:,6]
			top_indices = [i for i, conf in enumerate(det_conf) if conf >= conf_thresh]
			top_conf = det_conf[top_indices]
			top_xmin = det_xmin[top_indices]
			top_ymin = det_ymin[top_indices]
			top_xmax = det_xmax[top_indices]
			top_ymax = det_ymax[top_indices]

			for i in xrange(top_conf.shape[0]):
				xmin = int(round(top_xmin[i] * image.shape[1]))
				ymin = int(round(top_ymin[i] * image.shape[0]))
				xmax = int(round(top_xmax[i] * image.shape[1]))
				ymax = int(round(top_ymax[i] * image.shape[0]))
				xmin = max(1,xmin)
				ymin = max(1,ymin)
				xmax = min(image.shape[1]-1, xmax)
				ymax = min(image.shape[0]-1, ymax)
				score = top_conf[i]
				dt_result=[xmin,ymin,xmax,ymin,xmax,ymax,xmin,ymax,score]
				dt_results.append(dt_result)




		dt_results = sorted(dt_results, key=lambda x:-float(x[8]))
		nms_flag = nms(dt_results,0.3)

		for k,dt in enumerate(dt_results):
			  if nms_flag[k]:
				name = '%.2f'%(dt[8])
				xmin = dt[0]
				ymin = dt[1]
				xmax = dt[2]
				ymax = dt[5]
				coords = (xmin, ymin), xmax-xmin+1, ymax-ymin+1
				color = 'b'
				currentAxis.add_patch(plt.Rectangle(*coords, fill=False, edgecolor=color, linewidth=2))
				currentAxis.text(xmin, ymin, name, bbox={'facecolor':'white', 'alpha':0.5})

		#plt.savefig('./examples/results/demo_result.jpg')
		dest_img_path = image_dest_folder + image_name
		plt.savefig(str(dest_img_path))
    except Exception as e:
		print("Exception Occurs")
		continue

print('success')

```

**Comment by athmey** [comment]
Sure, I paste the code here directly. Sorry for the inconvenience.
```

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import os
import xml.dom.minidom
# %matplotlib inline
from nms import nms
plt.rcParams['figure.figsize'] = (10, 10)
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'

# Make sure that caffe is on the python path:
caffe_root = './'  # this file is expected to be in {caffe_root}/examples
os.chdir(caffe_root)
import sys
sys.path.insert(0, 'python')

import caffe
caffe.set_device(0)
caffe.set_mode_gpu()

model_def = './examples/TextBoxes/deploy.prototxt'
model_weights = './examples/TextBoxes/TextBoxes_icdar13.caffemodel'

#origin of this flag is True, for my own situation,since the gpu can not hold the "use_multi_scale" switch,i set this flag to false
use_multi_scale = True

if not use_multi_scale:
	scales=((700,700),)
else:
	#scales=((300,300),(700,700),(700,500),(700,300),(1600,1600))
	scales=((300,300),(700,700),(700,500),(700,300))

net = caffe.Net(model_def,      # defines the structure of the model
                model_weights,  # contains the trained weights
                caffe.TEST)     # use test mode (e.g., don't perform dropout)

dt_results=[]

#image_path='./examples/img/demo.jpg'
image_folder='./examples/img/'
image_list = os.listdir(image_folder)
image_dest_folder='./examples/results/'

conf_thresh = 0.6

for image in image_list:
    try:
		image_name = str(image)
		print(image_name)
	
		image_path = image_folder + image_name
		image=caffe.io.load_image(image_path)

		image_height,image_width,channels=image.shape
		plt.clf()
		plt.imshow(image)
		currentAxis = plt.gca()

		for scale in scales:
			print(scale)
			image_resize_height = scale[0]
			image_resize_width = scale[1]
			transformer = caffe.io.Transformer({'data': (1,3,image_resize_height,image_resize_width)})
			transformer.set_transpose('data', (2, 0, 1))
			transformer.set_mean('data', np.array([104,117,123])) # mean pixel
			transformer.set_raw_scale('data', 255)  # the reference model operates on images in [0,255] range instead of [0,1]
			transformer.set_channel_swap('data', (2,1,0))  # the reference model has channels in BGR order instead of RGB

			net.blobs['data'].reshape(1,3,image_resize_height,image_resize_width)
			transformed_image = transformer.preprocess('data', image)
			net.blobs['data'].data[...] = transformed_image
			# Forward pass.
			detections = net.forward()['detection_out']
			# Parse the outputs.
			det_label = detections[0,0,:,1]
			det_conf = detections[0,0,:,2]
			det_xmin = detections[0,0,:,3]
			det_ymin = detections[0,0,:,4]
			det_xmax = detections[0,0,:,5]
			det_ymax = detections[0,0,:,6]
			top_indices = [i for i, conf in enumerate(det_conf) if conf >= conf_thresh]
			top_conf = det_conf[top_indices]
			top_xmin = det_xmin[top_indices]
			top_ymin = det_ymin[top_indices]
			top_xmax = det_xmax[top_indices]
			top_ymax = det_ymax[top_indices]

			for i in xrange(top_conf.shape[0]):
				xmin = int(round(top_xmin[i] * image.shape[1]))
				ymin = int(round(top_ymin[i] * image.shape[0]))
				xmax = int(round(top_xmax[i] * image.shape[1]))
				ymax = int(round(top_ymax[i] * image.shape[0]))
				xmin = max(1,xmin)
				ymin = max(1,ymin)
				xmax = min(image.shape[1]-1, xmax)
				ymax = min(image.shape[0]-1, ymax)
				score = top_conf[i]
				dt_result=[xmin,ymin,xmax,ymin,xmax,ymax,xmin,ymax,score]
				dt_results.append(dt_result)




		dt_results = sorted(dt_results, key=lambda x:-float(x[8]))
		nms_flag = nms(dt_results,0.3)

		for k,dt in enumerate(dt_results):
			  if nms_flag[k]:
				name = '%.2f'%(dt[8])
				xmin = dt[0]
				ymin = dt[1]
				xmax = dt[2]
				ymax = dt[5]
				coords = (xmin, ymin), xmax-xmin+1, ymax-ymin+1
				color = 'b'
				currentAxis.add_patch(plt.Rectangle(*coords, fill=False, edgecolor=color, linewidth=2))
				currentAxis.text(xmin, ymin, name, bbox={'facecolor':'white', 'alpha':0.5})

		#plt.savefig('./examples/results/demo_result.jpg')
		dest_img_path = image_dest_folder + image_name
		plt.savefig(str(dest_img_path))
    except Exception as e:
		print("Exception Occurs")
		continue

print('success')
```

**Comment by MhLiao** [comment]
That's strange. Are your results normal when you run the original "demo.py“?

**Comment by athmey** [comment]
I just tried the origin code with the same image above(set multi_scales = False), the result is pretty good.
![demo_result](https://user-images.githubusercontent.com/29476966/29349318-b423db46-828b-11e7-874b-d3cc89007d69.jpg)

The only difference between my code and origin is that I have added a loop to traversal the directory.
Really confused

**Comment by MhLiao** [comment]
The "dt_results" in your code is never cleaned for different images. You should place it in the loop.

**Comment by athmey** [comment]
Perfect, tons of thanks for your kindness.
![demo](https://user-images.githubusercontent.com/29476966/29350405-0dba09dc-8291-11e7-9102-b118a61068cf.jpg)
![img_5](https://user-images.githubusercontent.com/29476966/29350406-0dbccf1e-8291-11e7-854e-e5d77119f0e9.jpg)
![test_img_3](https://user-images.githubusercontent.com/29476966/29350407-0dc18b26-8291-11e7-9214-c69f5780e734.jpg)

The result is pretty good now.

**Comment by gaalejandre** [comment]
@athmey can you please specify where to insert dt_results inside the loop, as suggested by @MhLiao ? Or pasting again the content of your final **demo.py** will be very much helpful. Thank you so much! I'm trying to learn about TextBoxes too, but no so familiar with python and deep learning.
