### ISSUE TITLE
python examples/TextBoxes/demo.py

### ISSUE THREAD

**Issue by Liampingfang** [MhLiao/TextBoxes#68]
Is the download procedure  necessary? I only execute the procedure of "installation" and "test" ,and appera the problem "ImportError: No module named shapely",when I run "python examples/TextBoxes/demo.py" how do I solve?

**Comment by MhLiao** [comment]
You need to install shapely by: pip install shapely

**Comment by Liampingfang** [comment]
thanks

**Comment by Liampingfang** [comment]
@MhLiao I put my code on the server instead of my computer ,when I run "pip install shapely " it appera the OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/Shapely-1.6.3.dist-info',I 
do not know if it is the different version of shapely between the code with the server.thank you in advance.
