### ISSUE TITLE
[Question] Reduce memory usage

### ISSUE THREAD

**Issue by gachiemchiep** [MhLiao/TextBoxes#73]
At first, thank you for your great work.

Secondly, do you have any advice about TextBoxes' memory usage. Currently eventhough i have 4GB in GPU memory, caffe still gave me "out of memory" message. 

  F1124 13:37:37.345823 30177 syncedmem.cpp:56] Check failed: error == cudaSuccess (2 vs. 0)  out of 
  memory
  *** Check failure stack trace: ***
  Aborted (core dumped)

  +-----------------------------------------------------------------------------+
  | NVIDIA-SMI 384.90                 Driver Version: 384.90                    |
  |-------------------------------+----------------------+----------------------+
  | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
  | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
  |===============================+======================+======================|
  |   0  Quadro M2000        Off  | 00000000:03:00.0 Off |                  N/A |
  | 56%   40C    P8    12W /  75W |    380MiB /  4029MiB |      0%      Default |
  +-------------------------------+----------------------+----------------------+

**Comment by MhLiao** [comment]
You can try to drop the scale of "1600*1600", which needs over 4GB memory.

**Comment by arsalan993** [comment]
Is this error coming while training or while running demo

**Comment by gachiemchiep** [comment]
@MhLiao 

Inside demo.py, i used only 300x300 but the problem is still the same "out of memory"

    scales = ((300, 300), )
    #if not use_multi_scale:
    #       scales=((300,300),) 
    #else:
    #       scales=((300,300),(700,700),(700,500),(700,300),(1600,1600))

@arsalan993 this error happen when  I run demo.py script.

**Comment by gachiemchiep** [comment]
Log file : https://pastebin.com/2zHFL0qW

Simple memory calculation lead to more than 9GB requirement.

Any guess?

**Comment by arsalan993** [comment]
Damns bro currently i am setting up a virtual machine inorder to execute this project,  then and only then i will be able to see if i get this error or not ... 
I will try to run it and lets see if i will get the same error or it

**Comment by gachiemchiep** [comment]
@arsalan993 good luck with that.

**Comment by arsalan993** [comment]
any success yet, 
either way can u please tell me whether this current code is able to recognize the text or it just detects it

**Comment by gachiemchiep** [comment]
Well, i only have 8GB in RAM memory, so both CPU and GPU options did not work so i gave up.
This code is only the text detector part.
