### ISSUE TITLE
On ICDAR website its is being told that TextBoxes performs End-to-End Text recognition, Here it is written detection only? 

### ISSUE THREAD

**Issue by arsalan993** [MhLiao/TextBoxes#74]
But here it is being written it is just the detector ,  what about recognition. I havent run it for now but i wanna know whether this code is capable of recognition or not. 
If not then came someone kindly share with me any github opensouce code for recognition on the text boxes. 
Thanks

**Comment by MhLiao** [comment]
The recognition code is here: https://github.com/bgshih/crnn
