### ISSUE TITLE
Check failed: error == cudaSuccess (2 vs. 0)  out of memory

### ISSUE THREAD

**Issue by Liampingfang** [MhLiao/TextBoxes#76]
What can I do for  the problem.thank you in advance

**Comment by MhLiao** [comment]
You may have no enough GPU memory.

**Comment by gaalejandre** [comment]
I used mode CPU, it worked and ran it about 15 mins in a single scale, (300,300). When I ran with GPU mode, the program crashes with that error.

**Comment by sungwonida** [comment]
My gear is GTX 1080 ti which has 11 GB of memory. I encountered the same issue.  
I'm currently working at `fd4d7a9`.

**Comment by sungwonida** [comment]
#87 helped me. I wish that helps someone else too.
