### ISSUE TITLE
Undefined function or variable 'polygon_intersect'

### ISSUE THREAD

**Issue by zhongzhuoyao** [MhLiao/TextBoxes#8]
@MhLiao 

I am running the  evaluation_nms code and there is a mistake in the code about "Undefined function or variable 'polygon_intersect'”. So, how do you actually implement this function.

Thanks a lot.

**Comment by MhLiao** [comment]
@zhongzhuoyao There is a download link of the compiled "polygon_intersect" on the github page.

**Comment by zhongzhuoyao** [comment]
@MhLiao  Can you show the detail of implementation?

**Comment by zjuDebug** [comment]
@zhongzhuoyao  Hello 
1> Download the mexa64 file from https://pan.baidu.com/s/1jIe9UWA and install MATLAB(not octave)
2> Place it in 'your_caffe_root/examples/TextBoxes' folder
3> run evaluation_nms.m()
