### ISSUE TITLE
error in create_data.sh when creating lmdb 

### ISSUE THREAD

**Issue by 19931991** [MhLiao/TextBoxes#80]
my error is:

neu@neu-H81MDV5:~/gzl/TextBoxes-TextBoxes$ ./data/VOC_gzl/create_data.sh
Traceback (most recent call last):
  File "/home/neu/gzl/TextBoxes-TextBoxes/data/VOC_gzl/../../scripts/create_annoset.py", line 103, in <module>
    label_map = caffe_pb2.LabelMap()
AttributeError: 'module' object has no attribute 'LabelMap'
Traceback (most recent call last):
  File "/home/neu/gzl/TextBoxes-TextBoxes/data/VOC_gzl/../../scripts/create_annoset.py", line 103, in <module>
    label_map = caffe_pb2.LabelMap()
AttributeError: 'module' object has no attribute 'LabelMap'

and I reference the code of ssd , and add  
export PYTHONPATH=/home/neu/gzl/TextBoxes-TextBoxes/python
into the .bashrc , and my part of bashrc is :

# added by tzf
# export PYTHONPATH=/home/neu/mxnet/python
# export PYTHONPATH=/home/neu/tzf/FCIS/mxnet/python

# added by Anaconda2 installer
#  export PATH="/home/neu/anaconda2/bin:$PATH"

# added by Anaconda3 installer
#  export PATH="/home/neu/anaconda3/bin:$PATH"

# wtx ssd
#  export PYTHONPATH=/home/neu/work/ssd/python

#gzl ssd
   export PYTHONPATH=/home/neu/gzl/TextBoxes-TextBoxes/python
   
# wtx caffe
  export PYTHONPATH=/home/neu/caffe-master/python
  export PATH=$PATH:/usr/local/MATLAB/R2016b/bin   
how can I solve the problem ???

**Comment by 19931991** [comment]
@MhLiao

**Comment by MhLiao** [comment]
You can try to add:
caffe_root = '/home/neu/gzl/TextBoxes-TextBoxes/' 
import os
os.chdir(caffe_root)
import sys
sys.path.insert(0, 'python')
import caffe
in the scripts/create_annoset.py

**Comment by 19931991** [comment]
Thanks for your guide,　this is my create_annoset.py . 
![image](https://user-images.githubusercontent.com/28551961/34547284-ff3bcb08-f134-11e7-945f-b29e8dac2041.png)

but it does not matter, 

neu@neu-H81MDV5:~/gzl/TextBoxes-TextBoxes$ ./data/VOC_gzl/create_data.sh
Traceback (most recent call last):
  File "/home/neu/gzl/TextBoxes-TextBoxes/data/VOC_gzl/../../scripts/create_annoset.py", line 110, in <module>
    label_map = caffe_pb2.LabelMap()
AttributeError: 'module' object has no attribute 'LabelMap'
Traceback (most recent call last):
  File "/home/neu/gzl/TextBoxes-TextBoxes/data/VOC_gzl/../../scripts/create_annoset.py", line 110, in <module>
    label_map = caffe_pb2.LabelMap()
AttributeError: 'module' object has no attribute 'LabelMap'
neu@neu-H81MDV5:~/gzl/TextBoxes-TextBoxes$ 

Are there any other ways?　Ｔhank you very much  !  @MhLiao

**Comment by 19931991** [comment]
and I try python create_annoset.py , the result is : 

neu@neu-H81MDV5:~/gzl/TextBoxes-TextBoxes$ cd scripts/
neu@neu-H81MDV5:~/gzl/TextBoxes-TextBoxes/scripts$ python create_annoset.py 
usage: create_annoset.py [-h] [--redo] [--anno-type ANNO_TYPE]
                         [--label-type LABEL_TYPE] [--backend BACKEND]
                         [--check-size] [--encode-type ENCODE_TYPE]
                         [--encoded] [--gray]
                         [--label-map-file LABEL_MAP_FILE] [--min-dim MIN_DIM]
                         [--max-dim MAX_DIM] [--resize-height RESIZE_HEIGHT]
                         [--resize-width RESIZE_WIDTH] [--shuffle]
                         [--check-label]
                         root listfile outdir exampledir
create_annoset.py: error: too few arguments
neu@neu-H81MDV5:~/gzl/TextBoxes-TextBoxes/scripts$ 

@MhLiao

**Comment by 19931991** [comment]
补充一下，我用的数据是ICDAR2013（边长有超过500的）, 要将ICDAR2013数据格式转换为VOC格式（网上说要求图片最大边长不超过500），我生成了.xml文件，trainval.txt+test.txt 文件，这两个文件是图片名称和xml一一对应的文件， 生成了test_name_size.txt文件，包含图片名称、宽和高。生成了labelmap.prototxt文件，包含标签信息。然后就运行create_data.sh 脚本，这个问题困扰了我很久，一直解决不了，是因为图片大小的问题吗？期待您的回信。非常感谢！@MhLiao

**Comment by 19931991** [comment]
I have solved the prolem by add export PYTHONPATH=/home/neu/gzl/TextBoxes-TextBoxes/python behind the path of caffe . Thank you very much！

**Comment by tahriribraq** [comment]
> I have solved the prolem by add export PYTHONPATH=/home/neu/gzl/TextBoxes-TextBoxes/python behind the path of caffe . Thank you very much！

Hello! I'm having the same problem trying to run create_annoset.py from this repo: https://github.com/weiliu89/caffe/tree/ssd
As you can see in the 1st screenshot, I don't have caffe root path at the top like you do, instead it's below all the parsers. I have tried to add the export pythonpath line above the caffe_root but still got syntax error. Could you please tell me what you meant by saying you added it "behind" the path of caffe? I'm stuck so your help will be much appreciated!
![1](https://user-images.githubusercontent.com/54651812/87759611-2ff80900-c7d4-11ea-955a-4b50f94ed730.png)
![2](https://user-images.githubusercontent.com/54651812/87759614-325a6300-c7d4-11ea-9e48-5634ff219578.png)
