### ISSUE TITLE
 Error parsing text-format caffe.NetParamete

### ISSUE THREAD

**Issue by aa642531** [MhLiao/TextBoxes#89]
hi,when i run "  python examples/TextBoxes/train_icdar13.py" ,it generated the follows:
Creating training net from train_net file: models/VGGNet/text/longer_conv_512x512/train.prototxt                                      
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 1
003:11: Message type "caffe.PriorBoxParameter" has no field named "offset".                           
Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: models/VGGNet/text/longer_conv_512x512/train.prototxt

**Comment by aa642531** [comment]
@MhLiao

**Comment by aa642531** [comment]
sorry,it' my problem.it has problem with my caffe path

**Comment by 19931991** [comment]
Do you have solved the prolem? Where did you modify the caffe path? Thank you very much!@aa642531

**Comment by aa642531** [comment]
@19931991 It' my problem.I had made the caffe of SSD before,so when i used this project,i added the previous caffe path to this project.The project had modified the caffe source,so you should build a private caffe for this project,and add the path.

**Comment by 19931991** [comment]
Thank you very much, I have solved the problem !
