### ISSUE TITLE
Training TextBoxes from scratch

### ISSUE THREAD

**Issue by YoungminBaek** [MhLiao/TextBoxes#92]
I am implementing TextBoxes using pytorch, and trying to reproduce the result on ICDAR2013 dataset.
I've trained my model with the pretrained VGG on SynthText dataset for 50k iterations, and finetuned on ICDAR 2013.
However the results seems to have additional small boxes in a single text region. (higher false 
positive ratio)

You mentioned that CRNN is used to improve the detection.
This mean that CRNN is used for finetuning? or just for inference step?

Additionally, do you have any guides to train TextBoxes correctly?

Thanks in advance.

**Comment by MhLiao** [comment]
@YoungminBaek Do you use hard negative mining?  CRNN is only used in the inference step.
