### ISSUE TITLE
how to get f-measure with evaluate_nms.m with single scale

### ISSUE THREAD

**Issue by gaalejandre** [MhLiao/TextBoxes#94]
Sir @MhLiao , I seem to be confused on how to get f-measure using evaluate_nms.m. Please enlighten me, anyone. Is it automatic, or do I have to tweak anything in the demo.py?

**Comment by MhLiao** [comment]
The evaluate_nms can output f-measure which may be slightly different from the official evaluation. You can use the online evaluation on http://rrc.cvc.uab.es
